### ISSUE TITLE
1.0.0 update broke package

### ISSUE THREAD

**Issue by walliski** [practicalmeteor/meteor-mocha-core#8]
In Windows 8.1 and 10 it seems as if the 1.0.0 update has broken this package. See https://github.com/practicalmeteor/meteor-mocha/issues/51.

**Comment by asdfjackal** [comment]
@walliski (in response to practicalmeteor/meteor-mocha#51) reverting those package changes and allowing an incompatible update appears to work, at least on initial testing. I backtracked through releases of mocha-core till the error stopped so it seems that the bug was introduced between 0.1.4 and 1.0.0-rc.1.

**Comment by jsep** [comment]
Thanks guys for reporting this, we are working to solve this!
